# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
#- name: apply common configuration to all nodes
#  hosts: all
#  user: root
#  roles:
#    - common
#

- name: Nginx
  hosts: front
  roles:
    - nginx

- name: Apache
  hosts: nginx
  roles:
    - apache

- name: Mysql
  hosts: mysql
  roles:
    - mysql
